### ISSUE TITLE
instead of 'pdf.' write 'PyPDF2.'

### ISSUE THREAD

**Issue by wlizama** [ronanpaixao/PyPDFTK#10]
https://github.com/ronanpaixao/PyPDFTK/blob/5c145900216aa7b21cb395d1142054b0ce97d2ee/pdf_images.py#L67

**Comment by ronanpaixao** [comment]
This is not correct, since I simplified the naming by using
```import PyPDF2 as pdf```
I used the same naming change in `pypdftk.py`.
